blank_issues_enabled: false
# Example entry:
#    name:
#    url:
#    about:
contact_links:
  - name: website
    url: https://wessel.gg
    about: My currently running portfolio
  - name: email
    url: contact@wessel.gg
    about: Feel free to email for any enquiries